[package]
name = "httpcat"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.31"
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1", features = ["full"] }
